#!/usr/bin/env python3
"""Embed sample CSVs into lib/embedded-samples.ts for offline packaging."""

from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
LOGS = ROOT / "logs"
OUT = ROOT / "lib" / "embedded-samples.ts"


def main() -> None:
    files = sorted(LOGS.glob("sample-*.csv"))
    if not files:
        raise SystemExit("no sample-*.csv files in logs/")
    lines = [
        "/** Auto-generated by scripts/embed-samples.py. Do not edit by hand. */",
        "",
        "export const EMBEDDED_SAMPLES: Record<string, string> = {",
    ]
    for path in files:
        lines.append(f"  {json.dumps(path.name)}: {json.dumps(path.read_text(encoding='utf-8'))},")
    lines.append("};")
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(files)} files)")


if __name__ == "__main__":
    main()
